#!/bin/bash

function usage() { 
    echo "Usage:"
    echo "$0 <file> <from_line_number> [<to_line_number>]"
}

if [ -z $2 ]; then
    usage
fi

FILE=$1
FROM=$2
TO=$3

AMOUNT=$(($3 - $2))

head $FILE -n$3 | tail -n$AMOUNT
